name: Deploy to Humanitec
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Humanitec
        run: |
          curl -X POST https://api.humanitec.io/orgs/zensar/apps/html-demo/envs/dev/deploys \
          -H "Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "env_id": "dev",
                "comment": "Triggering deployment from GitHub Actions"
              }'
